site_name: Heating Tracker Backend Docs
extra_css:
  - stylesheets/extra.css
theme:
  name: material  
  features:
    # - navigation.tabs
    # - navigation.sections
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# plugins:
#   - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/orgs/Atlas-B2023/repositories

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - mkdocstrings:
      custom_templates: "null"
      default_handler: python
      enable_inventory: null

copyright: |
  &copy; 2023 <a href="https://github.com/orgs/Atlas-B2023/repositories"  target="_blank" rel="noopener">WPI Atlas B23</a>
